/**
 * @fileoverview Adapter management REST API routes
 *
 * This module provides Express routes for managing external adapter plugins:
 * - Listing all registered adapters (built-in + external)
 * - Installing external adapters from npm packages or local paths
 * - Unregistering external adapters
 *
 * All routes require board-level authentication (assertBoard middleware).
 *
 * @module server/routes/adapters
 */

import { execFile } from "node:child_process";
import fs from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { Router } from "express";
import type { Db } from "@paperclipai/db";
import {
  listServerAdapters,
  findServerAdapter,
  findActiveServerAdapter,
  listEnabledServerAdapters,
  registerServerAdapter,
  registerLoadedExternalAdapter,
  unregisterServerAdapter,
  isOverridePaused,
  setOverridePaused,
} from "../adapters/registry.js";
import {
  listAdapterPlugins,
  addAdapterPlugin,
  compareAndSwapManagedAdapterPlugin,
  removeAdapterPlugin,
  getAdapterPluginByType,
  getAdapterPluginsDir,
  getDisabledAdapterTypes,
  setAdapterDisabled,
} from "../services/adapter-plugin-store.js";
import type { AdapterPluginRecord } from "../services/adapter-plugin-store.js";
import type { ServerAdapterModule, AdapterConfigSchema } from "../adapters/types.js";
import {
  loadExternalAdapterPackage,
  getUiParserSource,
  getOrExtractUiParserSource,
  reloadExternalAdapter,
} from "../adapters/plugin-loader.js";
import { logger } from "../middleware/logger.js";
import { assertBoard, assertInstanceAdmin, getActorInfo } from "./authz.js";
import { BUILTIN_ADAPTER_TYPES } from "../adapters/builtin-adapter-types.js";
import {
  installManagedAdapterBundle,
  verifyManagedAdapterBundleIdentity,
  verifyManagedAdapterPluginRecord,
  managedAdapterIdentityFromRecord,
  writeManagedAdapterTransitionReceipt,
} from "../services/managed-adapter-bundle.js";
import { instanceSettingsService, logActivity } from "../services/index.js";

const execFileAsync = promisify(execFile);
const PACKAGE_NAME = "@henkey/hermes-paperclip-adapter";

// ---------------------------------------------------------------------------
// Request / Response types
// ---------------------------------------------------------------------------

interface AdapterInstallRequest {
  /** npm package name (e.g., "droid-paperclip-adapter") or local path */
  packageName: string;
  /** True if packageName is a local filesystem path */
  isLocalPath?: boolean;
  /** Target version for npm packages (optional, defaults to latest) */
  version?: string;
  /** Explicit immutable installation authority; never treated as a local path. */
  installKind?: "npm" | "local_path" | "managed_immutable_bundle";
  /** Absolute content-addressed receipt generated by the adapter bundle builder. */
  installReceiptPath?: string;
  /** Exact operator-approved receipt digest. */
  installReceiptSha256?: string;
  /** Optimistic-lock identity. Null/omitted means the managed slot must be empty. */
  expectedCurrentBundleSha256?: string | null;
}

interface AdapterInfo {
  type: string;
  label: string;
  source: "builtin" | "external";
  modelsCount: number;
  loaded: boolean;
  disabled: boolean;
  /** True when an external plugin has replaced a built-in adapter of the same type. */
  overriddenBuiltin?: boolean;
  /** True when the external override for a builtin type is currently paused. */
  overridePaused?: boolean;
  version?: string;
  packageName?: string;
  isLocalPath?: boolean;
  installKind?: "npm" | "local_path" | "managed_immutable_bundle";
  bundleSha256?: string;
  manifestSha256?: string;
  installReceiptSha256?: string;
  /** Server-derived capability; never inferred from client session shape. */
  canManageManagedRuntime?: boolean;
  rollbackTargets?: Array<{
    bundleSha256: string;
    packageVersion: string;
    manifestSha256: string;
  }>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Resolve the adapter package directory (same rules as plugin-loader).
 */
function resolveAdapterPackageDir(record: AdapterPluginRecord): string {
  return record.localPath
    ? path.resolve(record.localPath)
    : path.resolve(getAdapterPluginsDir(), "node_modules", record.packageName);
}

/**
 * Read `version` from the adapter's package.json on disk.
 * This is the source of truth for what is actually installed (npm or local path).
 */
function readAdapterPackageVersionFromDisk(record: AdapterPluginRecord): string | undefined {
  try {
    const pkgDir = resolveAdapterPackageDir(record);
    const raw = fs.readFileSync(path.join(pkgDir, "package.json"), "utf-8");
    const v = JSON.parse(raw).version;
    return typeof v === "string" && v.trim().length > 0 ? v.trim() : undefined;
  } catch {
    return undefined;
  }
}

function buildAdapterInfo(
  adapter: ServerAdapterModule,
  externalRecord: AdapterPluginRecord | undefined,
  disabledSet: Set<string>,
  canManageManagedRuntime: boolean,
): AdapterInfo {
  const fromDisk = externalRecord ? readAdapterPackageVersionFromDisk(externalRecord) : undefined;
  return {
    type: adapter.type,
    label: adapter.type, // ServerAdapterModule doesn't have a separate "label" field; type serves as label
    source: externalRecord ? "external" : "builtin",
    modelsCount: (adapter.models ?? []).length,
    loaded: true, // If it's in the registry, it's loaded
    disabled: disabledSet.has(adapter.type),
    overriddenBuiltin: externalRecord ? BUILTIN_ADAPTER_TYPES.has(adapter.type) : undefined,
    overridePaused: BUILTIN_ADAPTER_TYPES.has(adapter.type) ? isOverridePaused(adapter.type) : undefined,
    // Prefer on-disk package.json so the UI reflects bumps without relying on store-only fields.
    version: fromDisk ?? externalRecord?.version,
    packageName: externalRecord?.packageName,
    isLocalPath: externalRecord?.localPath ? true : undefined,
    installKind: externalRecord?.installKind ?? (externalRecord?.localPath ? "local_path" : externalRecord ? "npm" : undefined),
    bundleSha256: externalRecord?.managedBundle?.bundleSha256,
    manifestSha256: externalRecord?.managedBundle?.manifestSha256,
    installReceiptSha256: externalRecord?.managedBundle?.installReceiptSha256,
    canManageManagedRuntime,
    rollbackTargets: canManageManagedRuntime ? externalRecord?.managedBundleHistory?.map((candidate) => ({
      bundleSha256: candidate.bundleSha256,
      packageVersion: candidate.packageVersion,
      manifestSha256: candidate.manifestSha256,
    })) : undefined,
  };
}

function requestCanManageManagedRuntime(req: Parameters<typeof assertInstanceAdmin>[0]): boolean {
  return req.actor.type === "board" &&
    (req.actor.source === "local_implicit" || req.actor.isInstanceAdmin === true);
}

async function logManagedAdapterTransition(
  db: Db,
  req: Parameters<typeof getActorInfo>[0],
  input: {
    operation: "install" | "rollback";
    phase: "authorized" | "completed";
    currentBundleSha256: string | null;
    targetBundleSha256: string;
    currentVerification: "verified" | "failed" | "not_present";
    transitionReceiptSha256: string;
    transitionReceiptPath: string;
  },
) {
  const actor = getActorInfo(req);
  const companyIds = await instanceSettingsService(db).listCompanyIds();
  await Promise.all(companyIds.map((companyId) => logActivity(db, {
    companyId,
    actorType: actor.actorType,
    actorId: actor.actorId,
    agentId: actor.agentId,
    runId: actor.runId,
    action: `adapter.managed_${input.operation}_${input.phase}`,
    entityType: "managed_adapter_runtime",
    entityId: input.targetBundleSha256,
    details: input,
  })));
}

/**
 * Normalize a local path that may be a Windows path into a WSL-compatible path.
 *
 * - Windows paths (e.g., "C:\\Users\\...") are converted via `wslpath -u`.
 * - Paths already starting with `/mnt/` or `/` are returned as-is.
 */
async function normalizeLocalPath(rawPath: string): Promise<string> {
  // Already a POSIX path (WSL or native Linux)
  if (rawPath.startsWith("/")) {
    return rawPath;
  }

  // Windows path detection: C:\ or C:/ pattern
  if (/^[A-Za-z]:[\\/]/.test(rawPath)) {
    try {
      const { stdout } = await execFileAsync("wslpath", ["-u", rawPath]);
      return stdout.trim();
    } catch (err) {
      logger.warn({ err, rawPath }, "wslpath conversion failed; using path as-is");
      return rawPath;
    }
  }

  return rawPath;
}

/**
 * Register an adapter module into the server registry, filling in
 * sessionManagement from the host.
 */
function registerWithSessionManagement(adapter: ServerAdapterModule): void {
  registerLoadedExternalAdapter(adapter);
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

export function adapterRoutes(db: Db) {
  const router = Router();

  /**
   * GET /api/adapters
   *
   * List all registered adapters (built-in + external).
   * Each entry includes whether the adapter is built-in or external,
   * its model count, and load status.
   */
  router.get("/adapters", async (req, res) => {
    assertBoard(req);

    const registeredAdapters = listServerAdapters();
    const externalRecords = new Map(
      listAdapterPlugins().map((r) => [r.type, r]),
    );
    const disabledSet = new Set(getDisabledAdapterTypes());

    const result: AdapterInfo[] = registeredAdapters.map((adapter) =>
      buildAdapterInfo(
        adapter,
        externalRecords.get(adapter.type),
        disabledSet,
        requestCanManageManagedRuntime(req),
      ),
    ).sort((a, b) => a.type.localeCompare(b.type));

    res.json(result);
  });

  /**
   * POST /api/adapters/install
   *
   * Install an external adapter from an npm package or local path.
   *
   * Request body:
   * - packageName: string (required) — npm package name or local path
   * - isLocalPath?: boolean (default false)
   * - version?: string — target version for npm packages
   */
  router.post("/adapters/install", async (req, res) => {
    assertBoard(req);

    const {
      packageName,
      isLocalPath = false,
      version,
      installKind = isLocalPath ? "local_path" : "npm",
      installReceiptPath,
      installReceiptSha256,
      expectedCurrentBundleSha256 = null,
    } = req.body as AdapterInstallRequest;

    if (installKind === "managed_immutable_bundle") {
      assertInstanceAdmin(req);
      if (packageName !== PACKAGE_NAME || typeof installReceiptPath !== "string" || !path.isAbsolute(installReceiptPath) ||
          typeof installReceiptSha256 !== "string" || !/^[a-f0-9]{64}$/.test(installReceiptSha256) ||
          (expectedCurrentBundleSha256 !== null && (typeof expectedCurrentBundleSha256 !== "string" || !/^[a-f0-9]{64}$/.test(expectedCurrentBundleSha256))) ||
          isLocalPath || version !== undefined) {
        res.status(400).json({
          error: "Managed immutable installation requires the exact Hermes adapter package name plus absolute installReceiptPath/installReceiptSha256, and forbids local-path/version flags.",
        });
        return;
      }
      try {
        const actor = getActorInfo(req);
        const occurredAt = new Date().toISOString();
        const existingRecord = getAdapterPluginByType("hermes_local");
        if (existingRecord && existingRecord.installKind !== "managed_immutable_bundle") {
          res.status(409).json({ error: "The hermes_local adapter slot is occupied by a non-managed installation." });
          return;
        }
        const current = existingRecord ? managedAdapterIdentityFromRecord(existingRecord) : null;
        if ((current?.bundleSha256 ?? null) !== expectedCurrentBundleSha256) {
          res.status(409).json({ error: "Active bundle changed before managed installation confirmation." });
          return;
        }
        let currentVerification: "verified" | "failed" | "not_present" = current ? "verified" : "not_present";
        if (existingRecord) {
          try {
            await verifyManagedAdapterPluginRecord(existingRecord);
          } catch (error) {
            currentVerification = "failed";
            logger.error({ error, bundleSha256: current?.bundleSha256 }, "Active managed adapter failed verification and is quarantined from future history");
          }
        }
        const managedBundle = await installManagedAdapterBundle({ installReceiptPath, installReceiptSha256 });
        const adapterModule = await loadExternalAdapterPackage(PACKAGE_NAME, managedBundle.packageRoot, managedBundle);
        if (adapterModule.type !== "hermes_local") throw new Error("Managed bundle did not construct the hermes_local adapter");
        const history = [
          ...(currentVerification === "verified" && existingRecord?.managedBundle ? [existingRecord.managedBundle] : []),
          ...(existingRecord?.managedBundleHistory ?? []),
        ].filter((candidate, index, all) =>
          candidate.bundleSha256 !== managedBundle.bundleSha256 &&
          all.findIndex((entry) => entry.bundleSha256 === candidate.bundleSha256) === index);
        const record: AdapterPluginRecord = {
          packageName: PACKAGE_NAME,
          version: managedBundle.packageVersion,
          type: adapterModule.type,
          installedAt: new Date().toISOString(),
          installKind: "managed_immutable_bundle",
          managedBundle,
          managedBundleHistory: history,
          bundlePath: managedBundle.archivePath,
          manifestSha256: managedBundle.manifestSha256,
          installReceiptPath: managedBundle.installReceiptPath,
          installReceiptSha256: managedBundle.installReceiptSha256,
        };
        const transition = await writeManagedAdapterTransitionReceipt({
          current,
          target: managedBundle,
          operation: "install",
          currentVerification,
          actor: { type: "user", id: actor.actorId },
          occurredAt,
        });
        record.managedTransitionReceiptPath = transition.receiptPath;
        record.managedTransitionReceiptSha256 = transition.receiptSha256;
        await logManagedAdapterTransition(db, req, {
          operation: "install",
          phase: "authorized",
          currentBundleSha256: current?.bundleSha256 ?? null,
          targetBundleSha256: managedBundle.bundleSha256,
          currentVerification,
          transitionReceiptSha256: transition.receiptSha256,
          transitionReceiptPath: transition.receiptPath,
        });
        if (!compareAndSwapManagedAdapterPlugin("hermes_local", expectedCurrentBundleSha256, record)) {
          res.status(409).json({ error: "Active bundle changed while the verified managed bundle was loading." });
          return;
        }
        registerWithSessionManagement(adapterModule);
        try {
          await logManagedAdapterTransition(db, req, {
            operation: "install",
            phase: "completed",
            currentBundleSha256: current?.bundleSha256 ?? null,
            targetBundleSha256: managedBundle.bundleSha256,
            currentVerification,
            transitionReceiptSha256: transition.receiptSha256,
            transitionReceiptPath: transition.receiptPath,
          });
        } catch (error) {
          logger.error({ error, transitionReceiptSha256: transition.receiptSha256 }, "Managed adapter install completed with immutable audit receipt but completion activity fanout failed");
        }
        res.status(201).json({
          type: adapterModule.type,
          packageName: PACKAGE_NAME,
          version: managedBundle.packageVersion,
          installKind: record.installKind,
          bundleSha256: managedBundle.bundleSha256,
          manifestSha256: managedBundle.manifestSha256,
          installReceiptSha256: managedBundle.installReceiptSha256,
          rollbackTargetCount: history.length,
          transitionReceiptPath: transition.receiptPath,
          transitionReceiptSha256: transition.receiptSha256,
          requiresRestart: false,
        });
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        logger.error({ err, installReceiptPath, installReceiptSha256 }, "Managed immutable adapter installation failed closed");
        res.status(422).json({ error: `Managed immutable adapter installation failed: ${message}` });
      }
      return;
    }

    if (!packageName || typeof packageName !== "string") {
      res.status(400).json({ error: "packageName is required and must be a string." });
      return;
    }

    // Strip version suffix if the UI sends "pkg@1.2.3" instead of separating it
    // e.g. "@henkey/hermes-paperclip-adapter@0.3.0" → packageName + version
    let canonicalName = packageName;
    let explicitVersion = version;
    const versionSuffix = packageName.match(/@(\d+\.\d+\.\d+.*)$/);
    if (versionSuffix) {
      // For scoped packages: "@scope/name@1.2.3" → "@scope/name" + "1.2.3"
      // For unscoped: "name@1.2.3" → "name" + "1.2.3"
      const lastAtIndex = packageName.lastIndexOf("@");
      if (lastAtIndex > 0 && !explicitVersion) {
        canonicalName = packageName.slice(0, lastAtIndex);
        explicitVersion = versionSuffix[1];
      }
    }

    try {
      let installedVersion: string | undefined;
      let moduleLocalPath: string | undefined;

      if (!isLocalPath) {
        // npm install into the managed directory
        const pluginsDir = getAdapterPluginsDir();
        const spec = explicitVersion ? `${canonicalName}@${explicitVersion}` : canonicalName;

        logger.info({ spec, pluginsDir }, "Installing adapter package via npm");

        await execFileAsync("npm", ["install", "--no-save", spec], {
          cwd: pluginsDir,
          timeout: 120_000,
        });

        // Read installed version from package.json
        try {
          const pkgJsonPath = path.join(pluginsDir, "node_modules", canonicalName, "package.json");
          const pkgContent = await import("node:fs/promises");
          const pkgRaw = await pkgContent.readFile(pkgJsonPath, "utf-8");
          const pkg = JSON.parse(pkgRaw);
          const v = pkg.version;
          installedVersion =
            typeof v === "string" && v.trim().length > 0 ? v.trim() : explicitVersion;
        } catch {
          installedVersion = explicitVersion;
        }
      } else {
        // Local path — normalize (e.g., Windows → WSL) and use the resolved path
        moduleLocalPath = path.resolve(await normalizeLocalPath(packageName));
        try {
          const pkgRaw = await readFile(path.join(moduleLocalPath, "package.json"), "utf-8");
          const v = JSON.parse(pkgRaw).version;
          if (typeof v === "string" && v.trim().length > 0) {
            installedVersion = v.trim();
          }
        } catch {
          // leave installedVersion undefined if package.json is missing
        }
      }

      // Load and register the adapter (use canonicalName for path resolution)
      const adapterModule = await loadExternalAdapterPackage(canonicalName, moduleLocalPath);

      // Check if this type conflicts with a built-in adapter
      if (BUILTIN_ADAPTER_TYPES.has(adapterModule.type)) {
        res.status(409).json({
          error: `Adapter type "${adapterModule.type}" is a built-in adapter and cannot be overwritten.`,
        });
        return;
      }

      // Check if already registered (indicates a reinstall/update)
      const existing = findServerAdapter(adapterModule.type);
      const isReinstall = existing !== null;
      if (existing) {
        unregisterServerAdapter(adapterModule.type);
        logger.info({ type: adapterModule.type }, "Unregistered existing adapter for replacement");
      }

      // Register the new adapter
      registerWithSessionManagement(adapterModule);

      // Persist the record (use canonicalName without version suffix)
      const record: AdapterPluginRecord = {
        packageName: canonicalName,
        localPath: moduleLocalPath,
        version: installedVersion ?? explicitVersion,
        type: adapterModule.type,
        installedAt: new Date().toISOString(),
        installKind: isLocalPath ? "local_path" : "npm",
      };
      addAdapterPlugin(record);

      logger.info(
        { type: adapterModule.type, packageName: canonicalName },
        "External adapter installed and registered",
      );

      res.status(201).json({
        type: adapterModule.type,
        packageName: canonicalName,
        version: installedVersion ?? explicitVersion,
        installedAt: record.installedAt,
        requiresRestart: isReinstall,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error({ err, packageName }, "Failed to install external adapter");

      // Distinguish npm errors from load errors
      if (message.includes("npm") || message.includes("ERR!")) {
        res.status(500).json({ error: `npm install failed: ${message}` });
      } else {
        res.status(500).json({ error: `Failed to install adapter: ${message}` });
      }
    }
  });

  router.post("/adapters/:type/managed-rollback", async (req, res) => {
    assertInstanceAdmin(req);
    const adapterType = req.params.type;
    const { expectedCurrentBundleSha256, targetBundleSha256, confirm } = req.body as {
      expectedCurrentBundleSha256?: string;
      targetBundleSha256?: string;
      confirm?: boolean;
    };
    if (adapterType !== "hermes_local" || confirm !== true ||
        typeof expectedCurrentBundleSha256 !== "string" || !/^[a-f0-9]{64}$/.test(expectedCurrentBundleSha256) ||
        typeof targetBundleSha256 !== "string" || !/^[a-f0-9]{64}$/.test(targetBundleSha256)) {
      res.status(400).json({ error: "Rollback requires hermes_local, confirm=true, and exact current/target bundle SHA-256 values." });
      return;
    }
    try {
      const actor = getActorInfo(req);
      const occurredAt = new Date().toISOString();
      const currentRecord = getAdapterPluginByType(adapterType);
      if (!currentRecord || currentRecord.installKind !== "managed_immutable_bundle" || !currentRecord.managedBundle) {
        res.status(409).json({ error: "The active adapter is not a managed immutable bundle." });
        return;
      }
      const current = managedAdapterIdentityFromRecord(currentRecord);
      if (current.bundleSha256 !== expectedCurrentBundleSha256) {
        res.status(409).json({ error: "Active bundle changed before rollback confirmation." });
        return;
      }
      const target = currentRecord.managedBundleHistory?.find((candidate) => candidate.bundleSha256 === targetBundleSha256);
      if (!target) {
        res.status(409).json({ error: "Requested rollback target is not in the verified managed history." });
        return;
      }
      let currentVerification: "verified" | "failed" = "verified";
      try {
        await verifyManagedAdapterPluginRecord(currentRecord);
      } catch (error) {
        currentVerification = "failed";
        logger.error({ error, bundleSha256: current.bundleSha256 }, "Active managed adapter failed verification; proceeding only with fully verified rollback target");
      }
      await verifyManagedAdapterBundleIdentity(target);
      const adapterModule = await loadExternalAdapterPackage(PACKAGE_NAME, target.packageRoot, target);
      if (adapterModule.type !== adapterType) throw new Error("Rollback bundle adapter type mismatch");
      const history = [
        ...(currentVerification === "verified" ? [current] : []),
        ...(currentRecord.managedBundleHistory ?? []).filter((candidate) => candidate.bundleSha256 !== target.bundleSha256),
      ]
        .filter((candidate, index, all) => all.findIndex((entry) => entry.bundleSha256 === candidate.bundleSha256) === index);
      const nextRecord: AdapterPluginRecord = {
        ...currentRecord,
        version: target.packageVersion,
        installedAt: new Date().toISOString(),
        managedBundle: target,
        managedBundleHistory: history,
        bundlePath: target.archivePath,
        manifestSha256: target.manifestSha256,
        installReceiptPath: target.installReceiptPath,
        installReceiptSha256: target.installReceiptSha256,
      };
      const transition = await writeManagedAdapterTransitionReceipt({
        current,
        target,
        operation: "rollback",
        currentVerification,
        actor: { type: "user", id: actor.actorId },
        occurredAt,
      });
      nextRecord.managedTransitionReceiptPath = transition.receiptPath;
      nextRecord.managedTransitionReceiptSha256 = transition.receiptSha256;
      await logManagedAdapterTransition(db, req, {
        operation: "rollback",
        phase: "authorized",
        currentBundleSha256: current.bundleSha256,
        targetBundleSha256: target.bundleSha256,
        currentVerification,
        transitionReceiptSha256: transition.receiptSha256,
        transitionReceiptPath: transition.receiptPath,
      });
      if (!compareAndSwapManagedAdapterPlugin(adapterType, expectedCurrentBundleSha256, nextRecord)) {
        res.status(409).json({ error: "Active bundle changed while the verified rollback target was loading." });
        return;
      }
      registerWithSessionManagement(adapterModule);
      try {
        await logManagedAdapterTransition(db, req, {
          operation: "rollback",
          phase: "completed",
          currentBundleSha256: current.bundleSha256,
          targetBundleSha256: target.bundleSha256,
          currentVerification,
          transitionReceiptSha256: transition.receiptSha256,
          transitionReceiptPath: transition.receiptPath,
        });
      } catch (error) {
        logger.error({ error, transitionReceiptSha256: transition.receiptSha256 }, "Managed adapter rollback completed with immutable audit receipt but completion activity fanout failed");
      }
      res.json({
        type: adapterType,
        installKind: "managed_immutable_bundle",
        priorBundleSha256: current.bundleSha256,
        activeBundleSha256: target.bundleSha256,
        activeVersion: target.packageVersion,
        rollbackTargetCount: history.length,
        transitionReceiptPath: transition.receiptPath,
        transitionReceiptSha256: transition.receiptSha256,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error({ err, adapterType, expectedCurrentBundleSha256, targetBundleSha256 }, "Managed adapter rollback failed closed");
      res.status(422).json({ error: `Managed adapter rollback failed: ${message}` });
    }
  });

  /**
   * PATCH /api/adapters/:type
   *
   * Enable or disable an adapter. Disabled adapters are hidden from agent
   * creation menus but remain functional for existing agents.
   *
   * Request body: { "disabled": boolean }
   */
  router.patch("/adapters/:type", async (req, res) => {
    assertBoard(req);

    const adapterType = req.params.type;
    const { disabled } = req.body as { disabled?: boolean };

    if (typeof disabled !== "boolean") {
      res.status(400).json({ error: "Request body must include { \"disabled\": true|false }." });
      return;
    }

    // Check that the adapter exists in the registry
    const existing = findServerAdapter(adapterType);
    if (!existing) {
      res.status(404).json({ error: `Adapter "${adapterType}" is not registered.` });
      return;
    }

    const changed = setAdapterDisabled(adapterType, disabled);

    if (changed) {
      logger.info({ type: adapterType, disabled }, "Adapter enabled/disabled");
    }

    res.json({ type: adapterType, disabled, changed });
  });

  /**
   * PATCH /api/adapters/:type/override
   *
   * Pause or resume an external adapter's override of a builtin type.
   * When paused, the server returns the builtin adapter for all new requests
   * (execute, listModels, config schema, etc.).  Already-running sessions
   * keep the adapter they started with.
   */
  router.patch("/adapters/:type/override", async (req, res) => {
    assertBoard(req);

    const adapterType = req.params.type;
    const { paused } = req.body as { paused?: boolean };

    if (typeof paused !== "boolean") {
      res.status(400).json({ error: "\"paused\" (boolean) is required in request body." });
      return;
    }

    if (!BUILTIN_ADAPTER_TYPES.has(adapterType)) {
      res.status(400).json({ error: `Type "${adapterType}" is not a builtin adapter.` });
      return;
    }

    const externalRecord = getAdapterPluginByType(adapterType);
    if (externalRecord?.installKind === "managed_immutable_bundle") {
      assertInstanceAdmin(req);
      res.status(409).json({
        error: "Managed immutable adapter overrides cannot be paused or resumed. Use an exact, confirmed managed transition instead.",
      });
      return;
    }

    const changed = setOverridePaused(adapterType, paused);

    logger.info({ type: adapterType, paused, changed }, "Adapter override toggle");

    res.json({ type: adapterType, paused, changed });
  });

  /**
   * DELETE /api/adapters/:type
   *
   * Unregister an external adapter. Built-in fallbacks cannot be removed, but
   * a legacy external override may be removed to reveal its fallback.
   */
  router.delete("/adapters/:type", async (req, res) => {
    assertBoard(req);

    const adapterType = req.params.type;

    if (!adapterType) {
      res.status(400).json({ error: "Adapter type is required." });
      return;
    }

    const externalRecord = getAdapterPluginByType(adapterType);

    // A built-in may have an active external override. The override is
    // removable, while the built-in fallback itself remains protected.
    if (BUILTIN_ADAPTER_TYPES.has(adapterType) && !externalRecord) {
      res.status(403).json({
        error: `Cannot remove built-in adapter "${adapterType}".`,
      });
      return;
    }

    // Managed immutable pointers may only move through the verified managed
    // install/rollback transitions. A legacy DELETE must never bypass those
    // provenance checks or erase rollback history.
    if (externalRecord?.installKind === "managed_immutable_bundle") {
      assertInstanceAdmin(req);
      res.status(409).json({
        error: "Managed immutable adapters cannot be removed through the legacy route. Install or roll back to a verified immutable bundle.",
      });
      return;
    }

    // Check that the adapter exists in the registry
    const existing = findServerAdapter(adapterType);
    if (!existing) {
      res.status(404).json({
        error: `Adapter "${adapterType}" is not registered.`,
      });
      return;
    }

    // Check that it's an external adapter
    if (!externalRecord) {
      res.status(404).json({
        error: `Adapter "${adapterType}" is not an externally installed adapter.`,
      });
      return;
    }

    // If installed via npm (has packageName but no localPath), run npm uninstall
    if (externalRecord.packageName && !externalRecord.localPath) {
      try {
        const pluginsDir = getAdapterPluginsDir();
        await execFileAsync("npm", ["uninstall", externalRecord.packageName], {
          cwd: pluginsDir,
          timeout: 60_000,
        });
        logger.info(
          { type: adapterType, packageName: externalRecord.packageName },
          "npm uninstall completed for external adapter",
        );
      } catch (err) {
        logger.warn(
          { err, type: adapterType, packageName: externalRecord.packageName },
          "npm uninstall failed for external adapter; continuing with unregister",
        );
      }
    }

    // Unregister from the runtime registry
    unregisterServerAdapter(adapterType);

    // Remove from the persistent store
    removeAdapterPlugin(adapterType);

    logger.info({ type: adapterType }, "External adapter unregistered and removed");

    res.json({ type: adapterType, removed: true });
  });

  /**
   * POST /api/adapters/:type/reload
   *
   * Reload an external adapter at runtime (for dev iteration without server restart).
   * Busts the ESM module cache, re-imports the adapter, and re-registers it.
   *
   * Cannot be used on built-in adapter types.
   */
  router.post("/adapters/:type/reload", async (req, res) => {
    assertBoard(req);

    const type = req.params.type;
    const storedRecord = getAdapterPluginByType(type);
    if (storedRecord?.installKind === "managed_immutable_bundle") {
      assertInstanceAdmin(req);
      res.status(409).json({
        error: "Managed immutable adapters cannot be reloaded in place. Install or roll back to a verified immutable bundle.",
      });
      return;
    }

    // Built-in adapters cannot be reloaded unless overridden by an external one
    if (BUILTIN_ADAPTER_TYPES.has(type) && !getAdapterPluginByType(type)) {
      res.status(400).json({ error: "Cannot reload built-in adapter." });
      return;
    }

    // Reload the adapter module (busts ESM cache, re-imports)
    try {
      const newModule = await reloadExternalAdapter(type);

      // Not found in the external adapter store
      if (!newModule) {
        res.status(404).json({ error: `Adapter "${type}" is not an externally installed adapter.` });
        return;
      }

      // Swap in the reloaded module
      unregisterServerAdapter(type);
      registerWithSessionManagement(newModule);
      configSchemaCache.delete(type);

      // Sync store.version from package.json (store may be missing version for local installs).
      const record = getAdapterPluginByType(type);
      let newVersion: string | undefined;
      if (record) {
        newVersion = readAdapterPackageVersionFromDisk(record);
        if (newVersion) {
          addAdapterPlugin({ ...record, version: newVersion });
        }
      }

      logger.info({ type, version: newVersion }, "External adapter reloaded at runtime");

      res.json({ type, version: newVersion, reloaded: true });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error({ err, type }, "Failed to reload external adapter");
      res.status(500).json({ error: `Failed to reload adapter: ${message}` });
    }
  });

  // ── POST /api/adapters/:type/reinstall ──────────────────────────────────
  // Reinstall an npm-sourced external adapter (pulls latest from registry).
  // Local-path adapters cannot be reinstalled — use Reload instead.
  //
  // This is a convenience shortcut for remove + install with the same
  // package name, but without the risk of losing the store record.
  router.post("/adapters/:type/reinstall", async (req, res) => {
    assertBoard(req);

    const type = req.params.type;

    if (BUILTIN_ADAPTER_TYPES.has(type) && !getAdapterPluginByType(type)) {
      res.status(400).json({ error: "Cannot reinstall built-in adapter." });
      return;
    }

    const record = getAdapterPluginByType(type);
    if (!record) {
      res.status(404).json({ error: `Adapter "${type}" is not an externally installed adapter.` });
      return;
    }

    if (record.installKind === "managed_immutable_bundle") {
      assertInstanceAdmin(req);
      res.status(409).json({
        error: "Managed immutable adapters cannot be reinstalled from npm. Install or roll back to an exact verified bundle.",
      });
      return;
    }

    if (record.localPath) {
      res.status(400).json({ error: "Local-path adapters cannot be reinstalled. Use Reload instead." });
      return;
    }

    try {
      const pluginsDir = getAdapterPluginsDir();

      logger.info({ type, packageName: record.packageName }, "Reinstalling adapter package via npm");

      await execFileAsync("npm", ["install", "--no-save", record.packageName], {
        cwd: pluginsDir,
        timeout: 120_000,
      });

      // Reload the freshly installed adapter
      const newModule = await reloadExternalAdapter(type);
      if (!newModule) {
        res.status(500).json({ error: "npm install succeeded but adapter reload failed." });
        return;
      }

      unregisterServerAdapter(type);
      registerWithSessionManagement(newModule);
      configSchemaCache.delete(type);

      // Sync store version from disk
      let newVersion: string | undefined;
      const updatedRecord = getAdapterPluginByType(type);
      if (updatedRecord) {
        newVersion = readAdapterPackageVersionFromDisk(updatedRecord);
        if (newVersion) {
          addAdapterPlugin({ ...updatedRecord, version: newVersion });
        }
      }

      logger.info({ type, version: newVersion }, "Adapter reinstalled from npm");

      res.json({ type, version: newVersion, reinstalled: true });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error({ err, type }, "Failed to reinstall adapter");
      res.status(500).json({ error: `Reinstall failed: ${message}` });
    }
  });

  // ── GET /api/adapters/:type/config-schema ────────────────────────────────
  // Serve a declarative config schema for an adapter's UI form fields.
  // The adapter's getConfigSchema() resolves all options (static and dynamic)
  // so the UI receives a fully hydrated schema in a single fetch.
  const configSchemaCache = new Map<string, { schema: AdapterConfigSchema; fetchedAt: number }>();
  const CONFIG_SCHEMA_TTL_MS = 30_000;

  router.get("/adapters/:type/config-schema", async (req, res) => {
    assertBoard(req);
    const { type } = req.params;

    const adapter = findActiveServerAdapter(type);
    if (!adapter) {
      res.status(404).json({ error: `Adapter "${type}" is not registered.` });
      return;
    }
    if (!adapter.getConfigSchema) {
      res.status(404).json({ error: `Adapter "${type}" does not provide a config schema.` });
      return;
    }

    const cached = configSchemaCache.get(type);
    if (cached && Date.now() - cached.fetchedAt < CONFIG_SCHEMA_TTL_MS) {
      res.json(cached.schema);
      return;
    }

    try {
      const schema = await adapter.getConfigSchema();
      configSchemaCache.set(type, { schema, fetchedAt: Date.now() });
      res.json(schema);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.error({ err, type }, "Failed to resolve config schema");
      res.status(500).json({ error: `Failed to resolve config schema: ${message}` });
    }
  });

  // ── GET /api/adapters/:type/ui-parser.js ─────────────────────────────────
  // Serve the self-contained UI parser JS for an adapter type.
  // This allows external adapters to provide custom run-log parsing
  // without modifying Paperclip's source code.
  //
  // The adapter package must export a "./ui-parser" entry in package.json
  // pointing to a self-contained ESM module with zero runtime dependencies.
  router.get("/adapters/:type/ui-parser.js", (req, res) => {
    assertBoard(req);
    const { type } = req.params;
    const source = getOrExtractUiParserSource(type);
    if (!source) {
      res.status(404).json({ error: `No UI parser available for adapter "${type}".` });
      return;
    }
    res.type("application/javascript").send(source);
  });

  return router;
}
