import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { agents } from "./agents.js";
import { heartbeatRuns } from "./heartbeat_runs.js";
import { issues } from "./issues.js";

export const contextLedgerEntries = pgTable(
  "context_ledger_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    runId: uuid("run_id").references(() => heartbeatRuns.id, { onDelete: "set null" }),
    agentId: uuid("agent_id").references(() => agents.id, { onDelete: "set null" }),
    issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
    taskKey: text("task_key"),
    cwd: text("cwd"),
    branch: text("branch"),
    adapterType: text("adapter_type").notNull(),
    adapterVersion: text("adapter_version"),
    promptClass: text("prompt_class").notNull(),
    promptBudgetVersion: text("prompt_budget_version").notNull(),
    promptFingerprint: text("prompt_fingerprint").notNull(),
    promptChars: integer("prompt_chars").notNull().default(0),
    estimatedPromptTokens: integer("estimated_prompt_tokens").notNull().default(0),
    componentHashes: jsonb("component_hashes").$type<Record<string, unknown>>(),
    artifactRefs: jsonb("artifact_refs").$type<Record<string, unknown>[]>(),
    contextPackRefs: jsonb("context_pack_refs").$type<Record<string, unknown>[]>(),
    sessionIdBefore: text("session_id_before"),
    sessionIdAfter: text("session_id_after"),
    commentCursor: jsonb("comment_cursor").$type<Record<string, unknown>>(),
    wakeCursor: jsonb("wake_cursor").$type<Record<string, unknown>>(),
    estimatedInputTokens: integer("estimated_input_tokens"),
    actualInputTokens: integer("actual_input_tokens"),
    actualOutputTokens: integer("actual_output_tokens"),
    cachedInputTokens: integer("cached_input_tokens"),
    budgetStatus: text("budget_status").notNull().default("ok"),
    budgetLimitTokens: integer("budget_limit_tokens"),
    responseClass: text("response_class").notNull().default("compact_status"),
    outputBudgetVersion: text("output_budget_version").notNull().default("output-economy.legacy"),
    estimatedOutputTokens: integer("estimated_output_tokens"),
    outputBudgetStatus: text("output_budget_status").notNull().default("ok"),
    outputBudgetLimitTokens: integer("output_budget_limit_tokens"),
    finalResponseChars: integer("final_response_chars"),
    finalResponseSentenceCount: integer("final_response_sentence_count"),
    finalResponseSha256: text("final_response_sha256"),
    finalResponseArtifactRefs: jsonb("final_response_artifact_refs").$type<Record<string, unknown>[]>(),
    finalOutcome: text("final_outcome"),
    finalBlocker: text("final_blocker"),
    receiptPaths: jsonb("receipt_paths").$type<string[]>(),
    redactionApplied: boolean("redaction_applied").notNull().default(true),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyRunIdx: index("context_ledger_entries_company_run_idx").on(table.companyId, table.runId),
    companyIssueIdx: index("context_ledger_entries_company_issue_idx").on(table.companyId, table.issueId),
    companyAgentCreatedIdx: index("context_ledger_entries_company_agent_created_idx").on(
      table.companyId,
      table.agentId,
      table.createdAt,
    ),
    promptFingerprintIdx: index("context_ledger_entries_prompt_fingerprint_idx").on(table.promptFingerprint),
  }),
);
