import {
  type AnyPgColumn,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { companies } from "./companies.js";
import { agents } from "./agents.js";
import { issues } from "./issues.js";
import { projects } from "./projects.js";

export const profitFlywheelWorkflows = pgTable(
  "profit_flywheel_workflows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "restrict" }),
    runId: text("run_id").notNull(),
    state: text("state").notNull().default("running"),
    currentStage: text("current_stage").notNull().default("dispatch"),
    sourceSchemaVersion: text("source_schema_version").notNull(),
    sourceDispatchPath: text("source_dispatch_path").notNull(),
    sourceDispatchHash: text("source_dispatch_hash").notNull(),
    targetRepo: text("target_repo").notNull(),
    targetWorkspaceRoot: text("target_workspace_root").notNull(),
    contractPath: text("contract_path").notNull(),
    contractSha256: text("contract_sha256").notNull(),
    contractSnapshot: jsonb("contract_snapshot").$type<Record<string, unknown>>().notNull(),
    correlationId: text("correlation_id").notNull(),
    traceId: text("trace_id").notNull(),
    portfolioOsExecutorAgentId: uuid("portfolio_os_executor_agent_id"),
    feedback: jsonb("feedback").$type<Record<string, unknown>>(),
    blockerCode: text("blocker_code"),
    blockerDetail: text("blocker_detail"),
    nextOwner: text("next_owner"),
    resumeCondition: text("resume_condition"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    stateCk: check("profit_flywheel_workflows_state_ck", sql`${table.state} in ('pending','running','retry','blocked','degraded','succeeded','failed','cancelled','safely_skipped')`),
    stageCk: check("profit_flywheel_workflows_stage_ck", sql`${table.currentStage} in ('research_intake','evidence_normalization','commercial_validation','council_decision','dispatch','implementation','qa','release','commercial_observation','learning')`),
    dispatchHashCk: check("profit_flywheel_workflows_dispatch_hash_ck", sql`${table.sourceDispatchHash} ~ '^[0-9a-f]{64}$'`),
    contractHashCk: check("profit_flywheel_workflows_contract_hash_ck", sql`${table.contractSha256} ~ '^[0-9a-f]{64}$'`),
    identityCk: check("profit_flywheel_workflows_identity_ck", sql`length(btrim(${table.runId})) between 1 and 200 and length(btrim(${table.correlationId})) between 1 and 200 and ${table.correlationId} ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]*$' and ${table.traceId} ~ '^[0-9a-f]{32}$' and length(btrim(${table.targetRepo})) > 0`),
    companyRunUq: uniqueIndex("profit_flywheel_workflows_company_run_uq").on(table.companyId, table.runId),
    idCompanyUq: uniqueIndex("profit_flywheel_workflows_id_company_uq").on(table.id, table.companyId),
    projectCompanyFk: foreignKey({
      name: "profit_flywheel_workflows_project_company_fk",
      columns: [table.projectId, table.companyId],
      foreignColumns: [projects.id, projects.companyId],
    }).onDelete("restrict"),
    portfolioOsExecutorCompanyFk: foreignKey({
      name: "profit_flywheel_workflows_portfolio_os_executor_company_fk",
      columns: [table.portfolioOsExecutorAgentId, table.companyId],
      foreignColumns: [agents.id, agents.companyId],
    }).onDelete("restrict"),
    portfolioOsExecutorIdx: index("profit_flywheel_workflows_portfolio_os_executor_agent_idx").on(table.portfolioOsExecutorAgentId),
    companyStateIdx: index("profit_flywheel_workflows_company_state_idx").on(table.companyId, table.state, table.updatedAt),
    correlationIdx: index("profit_flywheel_workflows_correlation_idx").on(table.correlationId),
  }),
);

export const profitFlywheelStageRuns = pgTable(
  "profit_flywheel_stage_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workflowId: uuid("workflow_id").notNull().references(() => profitFlywheelWorkflows.id, { onDelete: "cascade" }),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    stage: text("stage").notNull(),
    state: text("state").notNull().default("pending"),
    ownerPlane: text("owner_plane").notNull(),
    inputSchemaVersion: text("input_schema_version").notNull(),
    inputHash: text("input_hash").notNull(),
    sourceHashes: jsonb("source_hashes").$type<Record<string, string>>().notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    attemptCount: integer("attempt_count").notNull().default(0),
    maxAttempts: integer("max_attempts").notNull(),
    retryAt: timestamp("retry_at", { withTimezone: true }),
    linkedIssueId: uuid("linked_issue_id").references(() => issues.id, { onDelete: "set null" }),
    providerCapabilityClass: text("provider_capability_class").notNull(),
    providerRouteId: text("provider_route_id"),
    providerFamily: text("provider_family"),
    providerModel: text("provider_model"),
    providerModelVersion: text("provider_model_version"),
    providerPolicySha256: text("provider_policy_sha256"),
    providerRouteCoreSha256: text("provider_route_core_sha256"),
    providerRouteSha256: text("provider_route_sha256"),
    providerRouteSnapshot: jsonb("provider_route_snapshot").$type<Record<string, unknown>>(),
    transitionSourceStageRunId: uuid("transition_source_stage_run_id").references((): AnyPgColumn => profitFlywheelStageRuns.id, { onDelete: "restrict" }),
    transitionSourceOutputHash: text("transition_source_output_hash"),
    dispatchClaimId: uuid("dispatch_claim_id"),
    dispatchClaimedAt: timestamp("dispatch_claimed_at", { withTimezone: true }),
    concurrencyKey: text("concurrency_key").notNull(),
    concurrencyLimit: integer("concurrency_limit").notNull(),
    requiredReceipts: jsonb("required_receipts").$type<string[]>().notNull(),
    completionEvidence: jsonb("completion_evidence").$type<string[]>().notNull(),
    artifactCheckpoint: jsonb("artifact_checkpoint").$type<Record<string, unknown>>(),
    feedback: jsonb("feedback").$type<Record<string, unknown>>(),
    blockerCode: text("blocker_code"),
    blockerDetail: text("blocker_detail"),
    nextOwner: text("next_owner"),
    resumeCondition: text("resume_condition"),
    leaseOwner: text("lease_owner"),
    leaseActorType: text("lease_actor_type"),
    leaseActorId: text("lease_actor_id"),
    leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
    heartbeatAt: timestamp("heartbeat_at", { withTimezone: true }),
    correlationId: text("correlation_id").notNull(),
    traceId: text("trace_id").notNull(),
    spanId: text("span_id").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    stageCk: check("profit_flywheel_stage_runs_stage_ck", sql`${table.stage} in ('research_intake','evidence_normalization','commercial_validation','council_decision','dispatch','implementation','qa','release','commercial_observation','learning')`),
    stateCk: check("profit_flywheel_stage_runs_state_ck", sql`${table.state} in ('pending','running','retry','blocked','degraded','succeeded','failed','cancelled','safely_skipped')`),
    ownerCk: check("profit_flywheel_stage_runs_owner_ck", sql`${table.ownerPlane} in ('portfolio_os','paperclip','hermes')`),
    inputHashCk: check("profit_flywheel_stage_runs_input_hash_ck", sql`${table.inputHash} ~ '^[0-9a-f]{64}$'`),
    policyHashCk: check("profit_flywheel_stage_runs_policy_hash_ck", sql`${table.providerPolicySha256} is null or ${table.providerPolicySha256} ~ '^[0-9a-f]{64}$'`),
    routeHashCk: check("profit_flywheel_stage_runs_route_hash_ck", sql`(${table.providerRouteCoreSha256} is null and ${table.providerRouteSha256} is null and ${table.providerRouteSnapshot} is null or ${table.providerRouteCoreSha256} ~ '^[0-9a-f]{64}$' and ${table.providerRouteSha256} ~ '^[0-9a-f]{64}$' and ${table.providerRouteSnapshot} is not null) and (${table.transitionSourceOutputHash} is null or ${table.transitionSourceOutputHash} ~ '^[0-9a-f]{64}$')`),
    attemptCk: check("profit_flywheel_stage_runs_attempt_ck", sql`${table.attemptCount} >= 0 and ${table.maxAttempts} > 0 and ${table.attemptCount} <= ${table.maxAttempts}`),
    concurrencyCk: check("profit_flywheel_stage_runs_concurrency_ck", sql`${table.concurrencyLimit} > 0`),
    actorCk: check("profit_flywheel_stage_runs_actor_ck", sql`(${table.leaseActorType} is null and ${table.leaseActorId} is null) or (${table.leaseActorType} in ('agent','board','system') and ${table.leaseActorId} is not null)`),
    leaseCk: check("profit_flywheel_stage_runs_lease_ck", sql`(${table.leaseOwner} is null and ${table.leaseExpiresAt} is null and ${table.leaseActorType} is null and ${table.leaseActorId} is null and ${table.heartbeatAt} is null) or (${table.leaseOwner} is not null and ${table.leaseExpiresAt} is not null and ${table.leaseActorType} is not null and ${table.leaseActorId} is not null and ${table.heartbeatAt} is not null and ${table.state} = 'running')`),
    dispatchClaimCk: check("profit_flywheel_stage_runs_dispatch_claim_ck", sql`(${table.dispatchClaimId} is null and ${table.dispatchClaimedAt} is null) or (${table.dispatchClaimId} is not null and ${table.dispatchClaimedAt} is not null and ${table.state} = 'pending' and ${table.ownerPlane} = 'paperclip')`),
    identityCk: check("profit_flywheel_stage_runs_identity_ck", sql`length(btrim(${table.idempotencyKey})) between 1 and 1000 and length(btrim(${table.concurrencyKey})) between 1 and 500 and length(btrim(${table.correlationId})) between 1 and 200 and ${table.correlationId} ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]*$' and ${table.traceId} ~ '^[0-9a-f]{32}$' and ${table.spanId} ~ '^[0-9a-f]{16}$'`),
    companyIdempotencyUq: uniqueIndex("profit_flywheel_stage_runs_company_idempotency_uq").on(table.companyId, table.idempotencyKey),
    workflowStageInputUq: uniqueIndex("profit_flywheel_stage_runs_workflow_stage_input_uq").on(table.workflowId, table.stage, table.inputHash),
    idCompanyUq: uniqueIndex("profit_flywheel_stage_runs_id_company_uq").on(table.id, table.companyId),
    idWorkflowCompanyUq: uniqueIndex("profit_flywheel_stage_runs_id_workflow_company_uq").on(table.id, table.workflowId, table.companyId),
    workflowCompanyFk: foreignKey({
      name: "profit_flywheel_stage_runs_workflow_company_fk",
      columns: [table.workflowId, table.companyId],
      foreignColumns: [profitFlywheelWorkflows.id, profitFlywheelWorkflows.companyId],
    }).onDelete("cascade"),
    linkedIssueCompanyFk: foreignKey({
      name: "profit_flywheel_stage_runs_linked_issue_company_fk",
      columns: [table.linkedIssueId, table.companyId],
      foreignColumns: [issues.id, issues.companyId],
    }).onDelete("restrict"),
    transitionSourceLineageFk: foreignKey({
      name: "profit_flywheel_stage_runs_transition_source_lineage_fk",
      columns: [table.transitionSourceStageRunId, table.workflowId, table.companyId],
      foreignColumns: [table.id, table.workflowId, table.companyId],
    }).onDelete("restrict"),
    workflowStateIdx: index("profit_flywheel_stage_runs_workflow_state_idx").on(table.workflowId, table.state, table.updatedAt),
    issueIdx: index("profit_flywheel_stage_runs_issue_idx").on(table.linkedIssueId),
    leaseIdx: index("profit_flywheel_stage_runs_lease_idx").on(table.state, table.leaseExpiresAt),
  }),
);

export const profitFlywheelReceipts = pgTable(
  "profit_flywheel_receipts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    workflowId: uuid("workflow_id").notNull().references(() => profitFlywheelWorkflows.id, { onDelete: "cascade" }),
    stageRunId: uuid("stage_run_id").notNull().references(() => profitFlywheelStageRuns.id, { onDelete: "cascade" }),
    receiptType: text("receipt_type").notNull(),
    schemaVersion: text("schema_version").notNull(),
    contentHash: text("content_hash").notNull(),
    artifactRef: text("artifact_ref"),
    status: text("status").notNull().default("valid"),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    observedAtRaw: text("observed_at_raw"),
    expiresAtRaw: text("expires_at_raw"),
    attributes: jsonb("attributes").$type<Record<string, unknown>>().notNull(),
    correlationId: text("correlation_id").notNull(),
    traceId: text("trace_id").notNull(),
    spanId: text("span_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    hashCk: check("profit_flywheel_receipts_hash_ck", sql`${table.contentHash} ~ '^[0-9a-f]{64}$'`),
    statusCk: check("profit_flywheel_receipts_status_ck", sql`${table.status} in ('valid','invalid','expired','revoked','quarantined')`),
    expiryCk: check("profit_flywheel_receipts_expiry_ck", sql`${table.expiresAt} is null or ${table.expiresAt} > ${table.observedAt}`),
    stageTypeHashUq: uniqueIndex("profit_flywheel_receipts_stage_type_hash_uq").on(table.stageRunId, table.receiptType, table.contentHash),
    stageLineageFk: foreignKey({
      name: "profit_flywheel_receipts_stage_lineage_fk",
      columns: [table.stageRunId, table.workflowId, table.companyId],
      foreignColumns: [profitFlywheelStageRuns.id, profitFlywheelStageRuns.workflowId, profitFlywheelStageRuns.companyId],
    }).onDelete("cascade"),
    workflowCompanyFk: foreignKey({
      name: "profit_flywheel_receipts_workflow_company_fk",
      columns: [table.workflowId, table.companyId],
      foreignColumns: [profitFlywheelWorkflows.id, profitFlywheelWorkflows.companyId],
    }).onDelete("cascade"),
    workflowTypeIdx: index("profit_flywheel_receipts_workflow_type_idx").on(table.workflowId, table.receiptType, table.createdAt),
  }),
);

export const profitFlywheelEvents = pgTable(
  "profit_flywheel_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    workflowId: uuid("workflow_id").notNull().references(() => profitFlywheelWorkflows.id, { onDelete: "cascade" }),
    stageRunId: uuid("stage_run_id").references(() => profitFlywheelStageRuns.id, { onDelete: "cascade" }),
    eventType: text("event_type").notNull(),
    dedupeKey: text("dedupe_key").notNull(),
    fromState: text("from_state"),
    toState: text("to_state"),
    correlationId: text("correlation_id").notNull(),
    traceId: text("trace_id").notNull(),
    spanId: text("span_id"),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    attemptCount: integer("attempt_count").notNull().default(0),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    lastError: text("last_error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    fromStateCk: check("profit_flywheel_events_from_state_ck", sql`${table.fromState} is null or ${table.fromState} in ('pending','running','retry','blocked','degraded','succeeded','failed','cancelled','safely_skipped')`),
    toStateCk: check("profit_flywheel_events_to_state_ck", sql`${table.toState} is null or ${table.toState} in ('pending','running','retry','blocked','degraded','succeeded','failed','cancelled','safely_skipped')`),
    attemptCk: check("profit_flywheel_events_attempt_ck", sql`${table.attemptCount} >= 0`),
    workflowDedupeUq: uniqueIndex("profit_flywheel_events_workflow_dedupe_uq").on(table.workflowId, table.dedupeKey),
    workflowCompanyFk: foreignKey({
      name: "profit_flywheel_events_workflow_company_fk",
      columns: [table.workflowId, table.companyId],
      foreignColumns: [profitFlywheelWorkflows.id, profitFlywheelWorkflows.companyId],
    }).onDelete("cascade"),
    stageLineageFk: foreignKey({
      name: "profit_flywheel_events_stage_lineage_fk",
      columns: [table.stageRunId, table.workflowId, table.companyId],
      foreignColumns: [profitFlywheelStageRuns.id, profitFlywheelStageRuns.workflowId, profitFlywheelStageRuns.companyId],
    }).onDelete("cascade"),
    pendingIdx: index("profit_flywheel_events_pending_idx").on(table.processedAt, table.nextAttemptAt, table.createdAt),
  }),
);

export const profitFlywheelLeases = pgTable(
  "profit_flywheel_leases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    stageRunId: uuid("stage_run_id").notNull().references(() => profitFlywheelStageRuns.id, { onDelete: "cascade" }),
    scopeType: text("scope_type").notNull(),
    scopeKey: text("scope_key").notNull(),
    slot: integer("slot").notNull(),
    leaseOwner: text("lease_owner").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    scopeCk: check("profit_flywheel_leases_scope_ck", sql`${table.scopeType} in ('stage','repo','provider','agent')`),
    slotCk: check("profit_flywheel_leases_slot_ck", sql`${table.slot} >= 0`),
    ownerCk: check("profit_flywheel_leases_owner_ck", sql`length(btrim(${table.leaseOwner})) > 0`),
    scopeSlotUq: uniqueIndex("profit_flywheel_leases_scope_slot_uq").on(table.scopeType, table.scopeKey, table.slot),
    stageScopeUq: uniqueIndex("profit_flywheel_leases_stage_scope_uq").on(table.stageRunId, table.scopeType, table.scopeKey),
    stageCompanyFk: foreignKey({
      name: "profit_flywheel_leases_stage_company_fk",
      columns: [table.stageRunId, table.companyId],
      foreignColumns: [profitFlywheelStageRuns.id, profitFlywheelStageRuns.companyId],
    }).onDelete("cascade"),
    expiryIdx: index("profit_flywheel_leases_expiry_idx").on(table.expiresAt),
  }),
);

export const profitFlywheelProviderHealth = pgTable(
  "profit_flywheel_provider_health",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    routeId: text("route_id").notNull(),
    policySha256: text("policy_sha256").notNull(),
    policySchemaSha256: text("policy_schema_sha256").notNull(),
    provider: text("provider").notNull(),
    providerFamily: text("provider_family").notNull(),
    status: text("status").notNull(),
    failureClass: text("failure_class"),
    failureDetail: text("failure_detail"),
    resolvedModel: text("resolved_model"),
    resolvedVersion: text("resolved_version"),
    policyRouteCoreSha256: text("policy_route_core_sha256").notNull(),
    resolvedRouteSha256: text("resolved_route_sha256"),
    receiptPath: text("receipt_path"),
    receiptSha256: text("receipt_sha256"),
    receiptSchemaVersion: text("receipt_schema_version"),
    catalogEvidence: jsonb("catalog_evidence").$type<Record<string, unknown>>(),
    canaryKind: text("canary_kind").notNull(),
    canaryNonce: text("canary_nonce"),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    backoffUntil: timestamp("backoff_until", { withTimezone: true }),
    correlationId: text("correlation_id").notNull(),
    traceId: text("trace_id").notNull(),
    spanId: text("span_id").notNull(),
    details: jsonb("details").$type<Record<string, unknown>>().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    statusCk: check("profit_flywheel_provider_health_status_ck", sql`${table.status} in ('healthy','failed','quarantined')`),
    policyHashCk: check("profit_flywheel_provider_health_policy_hash_ck", sql`${table.policySha256} ~ '^[0-9a-f]{64}$' and ${table.policySchemaSha256} ~ '^[0-9a-f]{64}$'`),
    receiptHashCk: check("profit_flywheel_provider_health_receipt_hash_ck", sql`${table.receiptSha256} is null or ${table.receiptSha256} ~ '^[0-9a-f]{64}$'`),
    routeHashCk: check("profit_flywheel_provider_health_route_hash_ck", sql`${table.policyRouteCoreSha256} ~ '^[0-9a-f]{64}$' and (${table.resolvedRouteSha256} is null or ${table.resolvedRouteSha256} ~ '^[0-9a-f]{64}$')`),
    failureClassCk: check("profit_flywheel_provider_health_failure_class_ck", sql`${table.failureClass} is null or ${table.failureClass} in ('provider_auth','provider_billing','provider_capability_mismatch','provider_malformed_response','provider_quota','provider_rate_limit','provider_security_compromise','transient_network','process_lost')`),
    healthyEvidenceCk: check("profit_flywheel_provider_health_healthy_evidence_ck", sql`${table.status} <> 'healthy' or (${table.failureClass} is null and ${table.resolvedModel} is not null and ${table.resolvedVersion} is not null and ${table.resolvedRouteSha256} is not null and ${table.receiptPath} is not null and ${table.receiptSha256} is not null and ${table.receiptSchemaVersion} is not null)`),
    canaryCk: check("profit_flywheel_provider_health_canary_ck", sql`${table.canaryKind} in ('zero_token','minimal_token','work_bearing')`),
    failuresCk: check("profit_flywheel_provider_health_failures_ck", sql`${table.consecutiveFailures} >= 0`),
    expiryCk: check("profit_flywheel_provider_health_expiry_ck", sql`${table.expiresAt} > ${table.observedAt}`),
    routePolicyUq: uniqueIndex("profit_flywheel_provider_health_route_policy_uq").on(table.companyId, table.routeId, table.policySha256, table.policySchemaSha256),
    freshnessIdx: index("profit_flywheel_provider_health_freshness_idx").on(table.companyId, table.status, table.expiresAt, table.backoffUntil),
  }),
);

export const profitFlywheelMigrationRuns = pgTable(
  "profit_flywheel_migration_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    migrationVersion: text("migration_version").notNull(),
    state: text("state").notNull(),
    planSha256: text("plan_sha256").notNull(),
    intentReceiptPath: text("intent_receipt_path").notNull(),
    intentReceiptSha256: text("intent_receipt_sha256").notNull(),
    providerPolicySha256: text("provider_policy_sha256").notNull(),
    providerPolicySchemaSha256: text("provider_policy_schema_sha256").notNull(),
    rollbackSnapshot: jsonb("rollback_snapshot").$type<Record<string, unknown>>().notNull(),
    result: jsonb("result").$type<Record<string, unknown>>().notNull(),
    appliedAt: timestamp("applied_at", { withTimezone: true }),
    rolledBackAt: timestamp("rolled_back_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    stateCk: check("profit_flywheel_migration_runs_state_ck", sql`${table.state} in ('applied','rolled_back')`),
    hashCk: check("profit_flywheel_migration_runs_hash_ck", sql`${table.planSha256} ~ '^[0-9a-f]{64}$' and ${table.intentReceiptSha256} ~ '^[0-9a-f]{64}$' and ${table.providerPolicySha256} ~ '^[0-9a-f]{64}$' and ${table.providerPolicySchemaSha256} ~ '^[0-9a-f]{64}$'`),
    planUq: uniqueIndex("profit_flywheel_migration_runs_plan_uq").on(table.planSha256),
  }),
);
